improve: /stat and /stat_tot commands
UNICT-DMI/Telegram-DMI-Bot pull request #117
Opened 2020-10-25 13:58 UTC by TendTo

Ora la lista di comandi è ordinata secondo il numero di volte che un comando è stato utilizzato, e ci sono 2 info aggiuntive, cioè il totale degli utilizzi e la media per comando [closes #115].

Il risultato è il seguente
![Cattura](https://user-images.githubusercontent.com/65033249/97109044-65fd3100-16d1-11eb-91c6-fda9ff7fd765.JPG)

Non sono sicuro sul come realizzare il graph: oltre a dover usare un'apposita libreria, penso che un grafico (a torta o a barre) sarebbe un po' poco leggibile perché ci sono tante labels (comandi). Se avete in mente qualcosa suggerite

2020-10-25 14:29 UTC, Guberlo commented
Potremmo fare dei grafici solamente per le top x, così da avere meno casino nel grafico e vedere comunque qualcosa di più intuitivo

2020-10-25 15:16 UTC, drendog commented
per comodità si potrebbe linkare ad una pagina che mostra un grafico

2020-10-25 15:59 UTC, TendTo commented
Ok, ho provato ad aggiungere un semplice grafico a barre, e questo è il risultato
![Cattura](https://user-images.githubusercontent.com/65033249/97112072-96999680-16e2-11eb-869e-18fb4e9ad756.JPG)

> Potremmo fare dei grafici solamente per le top x, così da avere meno casino nel grafico e vedere comunque qualcosa di più intuitivo

Ho seguito il consiglio e per adesso mi limito a prendere le prime 10

>per comodità si potrebbe linkare ad una pagina che mostra un grafico

Funzionerebbe, a patto di avere una pagina da cui mostrare il grafico. A meno che non ci sia qualche api che tu gli fornisci i dati e ti prepara un'immagine di grafico (idea interessante a prescindere)

Il fastidioso il fatto che ho dovuto aggiungere la libreria [matplotlib](https://matplotlib.org/), per cui vedete se secondo voi ne vale la pena o se vi viene in mente qualche alternativa

2020-10-25 16:21 UTC, drendog approved these changes

2020-10-26 13:30 UTC, Helias commented on module/stats.py
>          days = 30
```suggestion
    days = 30
    if context.args and int(context.args[0]) > 0:
        days = int(context.args[0])
```

che ne pensi? :grin:

2020-10-26 13:35 UTC, Helias requested changes

2020-10-26 13:35 UTC, Helias commented on module/stats.py
> +        if str(row[0]) not in ("leiCheNePensaSignorina", "smonta_portoni", "santino", "bladrim", "prof_sticker"):
put `("leiCheNePensaSignorina", "smonta_portoni", ...)` in a separated variable like `easter_egg`, I think it's better

2020-10-26 13:35 UTC, Helias commented on module/stats.py
> +        query = "SELECT Type, n FROM (SELECT Type, COUNT(chat_id) as n FROM stat_list GROUP BY Type) ORDER BY n DESC;"
You can't just use only one query inside than two nested for ordering?
probably because sqlite can't order by a count() variable?

2020-10-26 13:35 UTC, Helias commented on module/stats.py
> +        query = "SELECT Type, n FROM (SELECT Type, COUNT(chat_id) as n FROM stat_list GROUP BY Type) ORDER BY n DESC;"
like 
```sql
SELECT Type, COUNT(chat_id) AS n FROM stat_list GROUP BY Type ORDER BY n DESC;
```

2020-10-26 13:35 UTC, Helias commented on module/stats.py
> +    # Prende solo i primi 10 valori
may we should keep the comment in english? I don't know :grin:

2020-10-26 18:25 UTC, Helias commented on module/stats.py
> +    rows = [row for row in conn.execute(query).fetchall() if row[0] not in EASTER_EGG]
wonderful

2020-10-26 18:26 UTC, Helias approved these changes

2020-10-26 18:27 UTC, Helias commented
possiamo mergiare

2020-10-26 20:47 UTC, merged