Dockerfile-fix
UNICT-DMI/Telegram-DMI-Bot pull request #144
Opened 2021-03-10 17:41 UTC by codesimo

Il vecchio dockerfile non funzionava, l'ho aggiornato usando ubuntu 20.04 come base e applicando tutti i fix descritti nel readme.
Inoltre credo che il file token.conf non venga più usato.

2021-03-10 19:03 UTC, Helias requested changes

2021-03-10 19:03 UTC, Helias commented on Dockerfile
> +#Fix to install software-properties-common, needed to use add-apt-repository
```suggestion
# fix to install software-properties-common, needed to use add-apt-repository
```

2021-03-10 19:03 UTC, Helias commented on Dockerfile
> +#Fix libqtwebkit-dev missing
```suggestion
# fix libqtwebkit-dev missing
```

2021-03-10 19:03 UTC, Helias commented on Dockerfile
> +#Fix webkit-server
```suggestion
# fix webkit-server
```

2021-03-10 19:03 UTC, Helias commented on Dockerfile
>  RUN pip3 install -r $DMI_BOT_DIR/dmibot/requirements.txt
Too much spaces here, be coherent with the rest

2021-03-10 19:03 UTC, Helias commented on Dockerfile
> +#RUN echo $TOKEN > $DMI_BOT_DIR/dmibot/config/token.conf
useless comment, remove it
```suggestion
```

2021-03-10 19:04 UTC, Helias requested changes

2021-03-12 12:50 UTC, codesimo commented
I removed dryscrape and replaced it with requests in local, but TendTo did the same creating a PR. He added some logging stuff and changed how the dockerfile works, so this PR becomes useless.
Closing

2021-03-12 12:50 UTC, closed without merging